# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14edf1415e49bef5e9d87b4d932341c53a433559dede71065b20688ba19887c65283b818a9a214895556da3a8347599c0f47ab6fef3958cd9ca44b3e14e55a7e

test:
  secret_key_base: c70da86483a6b663aed9c69581d234ca6a7c05aed5e3bf0162b83a350f94d555c880dcb82ce373bb9d99211d0f94b726b407beacc8800e33f5332740d9b43f5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
